# Generated by Django 5.0.7 on 2024-09-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
